### PR TITLE
Add Firefox 37.

### PR DESCRIPTION
**Pull request by jdalton**
This adds v37 minus the icon because I couldn't get it to generate

### CODE REVIEW

**Comment by omgmog** [comment]
thanks!

not sure about the script not working, but I've added the icon myself

**Comment by omgmog** [comment]
Could be that imagemagick can't see your system fonts, you can tell imagemagick where to find your fonts using a solution like this: http://gothick.org.uk/2008/03/14/using-os-x-fonts-in-imagemagick/

**Comment by jdalton** [comment]
Thanks!

**Comment by omgmog** [comment]
Just an update to this, as I've got a new Mac I had the same issue!

To fix, install ghostscript along with imagemagick:

``` shell
$ brew install imagemagick gs
```

**Comment by jdalton** [comment]
> To fix, install ghostscript along with imagemagick

That did it! Thanks!

**Pull request merged**
